export const ADD_TASK = 'ADD_TASK';
export const ADD_TASKS = 'ADD_TASKS';
export const CHANGE_IS_OPEN_ADD_TASK_MODAL = 'CHANGE_IS_OPEN_ADD_TASK_MODAL';
export const CHANGE_IS_OPEN_EDIT_TASK_MODAL = 'CHANGE_IS_OPEN_EDIT_TASK_MODAL';
